service: kevinky-mod
provider:
  name: aws
  region: eu-west-3
  runtime: nodejs20.x
  environment:
    DeeplKEY: ${env:DeeplKEY}
    DISCORD_WEBHOOK_URL: ${env:DISCORD_WEBHOOK_URL}
    DISCORD_WEBHOOK_URL_SPANISH: ${env:DISCORD_WEBHOOK_URL_SPANISH}
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
